### ISSUE TITLE
某种配置下错误

### ISSUE THREAD

**Issue by WillZ5** [zhuhaow/SpechtLite#48]
使用如下配置，whitelist 文件为：https://github.com/geekpi/SpechtLiteConf/blob/master/conf/whitelist
无法打开youtube.com等网站。
```
port: 9090
adapter:
  - id: proxy
    type: ss
    method: chacha20
    host: xxxxx
    port: 80
    password: xxxxxxx
    protocol: verify_sha1
  - id: speed
    type: SPEED
    adapters:
      - id: proxy
        delay: 0
      - id: direct
        delay: 0
  - id: reject
    type: reject
    delay: 300
rule:
  - type: list
    file: ~/.SpechtLite/whitelist
    adapter: direct
  - type: iplist
    file: ~/.SpechtLite/proxyiprange
    adapter: proxy
  - type: list
    file: ~/.SpechtLite/rejectlist
    adapter: reject
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: country
    country: --
    match: true
    adapter: proxy
  - type: DNSFail
    adapter: proxy
  - type: all
    adapter: proxy

```
以youtube.com 为例，此配置文件无法打开网页，log 显示：`2017/02/04 18:19:03:337  Request: www.youtube.com Type: DirectAdapter Rule: <DomainListRule>`
，但whitelist 中并没有youtube 有关域名。

**Comment by zhuhaow** [comment]
`e\.com$`，顺带一说，这种除了拖慢程序什么用没有的列表最好不要用了

**Comment by WillZ5** [comment]
好的，再麻烦一下，如下配置，是不是可以做到类似COW 自动选择是否代理的功能？如果是那为什么这个配置下，有些网址例如google.com，youtube.com可以打开，而有些网址例如imgchili.net 就无法打开？
纠结了很长时间了。

```
port: 9090
adapter:
  - id: virmach
    type: ss
    method: chacha20
    host: *******
    port: 80
    password: *******
  - id: proxy
    type: SPEED
    adapters:
      - id: direct
        delay: 0
      - id: virmach
        delay: 300
rule:
  - type: country
    country: --
    match: true
    adapter: direct
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: DNSFail
    adapter: proxy
  - type: all
    adapter: proxy
```
