### ISSUE TITLE
not compatible with Tor

### ISSUE THREAD

**Issue by nerdDan** [zhuhaow/SpechtLite#55]
Tor requires an underlying proxy (VPN or ShadowSocks) layer in China. I was trying to config ShadowSocks + Tor + SpechtLite, so that when I visit a onion website Tor would be utilized automatically.

I have this line in my `torrc`,

```
Socks5Proxy 127.0.0.1:9091
```

and these lines in my SpechtLite config file.

```
port: 9090
adapter:
  ...
  - id: tor
    type: socks5
    host: socks5.server
    port: 9050
rule:
  - type: list
    file: ~/.SpechtLite/onion.txt
    adapter: tor
  ...
```

Such configuration does not work since it causes a recursive proxy route.

Any suggestions?

**Comment by zhuhaow** [comment]
It should not form a loop if you set up everything correctly.

Websites with `*.onion` will go from spechtlite to tor, then tor connects to gateway through spechtlite again. But gateway is not a `*.onion` site anymore, so I don't see why it would go back to tor again.

**Comment by nerdDan** [comment]
why "gateway is not a *.onion site anymore"?

I get an `ERR_EMPTY_RESPONSE` when visiting a `.onion` page.

**Comment by zhuhaow** [comment]
Do you understand what you are doing? 
How can you connect to a gateway with *.onion as address?

**Comment by nerdDan** [comment]
What is "gateway"? What makes my configuration wrong?

**Comment by zhuhaow** [comment]
You can paste all you config here

**Comment by nerdDan** [comment]
SpechtLite config
```yaml
# Note there is another SOCKS5 proxy server starts at port+1 automatically.
port: 9090
adapter:
  # There is a 'direct' adapter that connect directly to target host without proxy.
  - id: dong
    type: ss
    host: 45.78.xxx.xxx
    port: 443
    password: xxxxxxx
    method: AES-256-CFB
    protocol: origin
    obfs: origin
  - id: speed
    type: SPEED
    adapters:
      - id: dong
        # Delay in milliseconds.
        delay: 300
      - id: direct
        delay: 0
  - id: tor
    type: socks5
    host: socks5.server
    port: 9050
rule:
  - type: list
    file: ~/.SpechtLite/onion.txt
    adapter: tor
  - type: country
    country: CN
    match: true
    adapter: direct
  # When the location is unknown. Usually this means this is resolved an Intranet IP.
  - type: country
    country: --
    match: true
    adapter: direct
  # When the DNS lookup of the host fails.
  - type: DNSFail
    adapter: speed
  - type: all
    adapter: dong
```

`onion.txt`
```
\.onion
```

`torrc`
```
Socks5Proxy 127.0.0.1:9091
```

**Comment by zhuhaow** [comment]
Seems fine. How do you know there is a loop?

**Comment by zhuhaow** [comment]
What did the log of spechtlite say

**Comment by ChengLuffy** [comment]
```
  - id: tor
    type: socks5
    host: socks5.server
    port: 9050
rule:
  - type: list
    file: ~/.SpechtLite/onion.txt
    adapter: tor
```

tor
```
Socks5Proxy 127.0.0.1:9091
```
request -> spechtLite -> onion.txt -> tor -> spechtLite ->...
