### ISSUE TITLE
IP rules with ipv6 makes no difference

### ISSUE THREAD

**Issue by balthild** [zhuhaow/SpechtLite#70]
Configuration file
```yaml
port: 8090

adapter:
  - id: ss-local
    type: socks5
    host: 127.0.0.1
    port: 1080

rule:
  ...

  - type: iplist
    adapter: direct
    file: ~/.SpechtLite/DirectIPList

  - type: all
    adapter: ss-local
```

~/.SpechtLite/DirectIPList
```
...
0:0:0:0:0:0:0:0/128 ( Match all IPv6 addresses. Also tried ::0/128 )
```

Log
```
2017/10/06 21:15:57:292  Request: ipv6.google.com.hk Type: SOCKS5Adapter Rule: <AllRule>
```

Expected behaviour:
`ipv6.google.com.hk` goes to `direct` adapter.
