### ISSUE TITLE
The yaml parser is too strict

### ISSUE THREAD

**Issue by qiuwei** [zhuhaow/SpechtLite#75]
Arrays without indent cannot be parsed correctly

For example
```
adapter:
- id: adapter1
   host: blabla
- id: adapter2
   host: blabla
```

cannot be parsed correctly.
