### ISSUE TITLE
[Feature Request] Support invoke an external program when start

### ISSUE THREAD

**Issue by wd** [zhuhaow/SpechtLite#83]
I noticed SpechtLite only support ss now.  But there are lots of similar programs like v2ray, brook, etc. They all support work like ss (after running, can provide a socks proxy), so maybe you can consider to add support something like below, and this would be great.
```
- adapter3:
   type: external
   exec: /path/to/program
   args:
      -arg1
      -arg2
   local-socks-port: 1080
```
And I know , I can run the program by my myself and add an socks adapter. You know, this is a just an advice, support or not, it's up to you. 

Thanks for this great tools.
